//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectRunner.Strings {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TimezonesLocations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TimezonesLocations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectRunner.Strings.TimezonesLocations", typeof(TimezonesLocations).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Europe.
        /// </summary>
        public static string CONTINENT_EUROPE {
            get {
                return ResourceManager.GetString("CONTINENT_EUROPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albania.
        /// </summary>
        public static string EUROPE_ALBANIA {
            get {
                return ResourceManager.GetString("EUROPE_ALBANIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andorra.
        /// </summary>
        public static string EUROPE_ANDORRA {
            get {
                return ResourceManager.GetString("EUROPE_ANDORRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Austria.
        /// </summary>
        public static string EUROPE_AUSTRIA {
            get {
                return ResourceManager.GetString("EUROPE_AUSTRIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belarus.
        /// </summary>
        public static string EUROPE_BELARUS {
            get {
                return ResourceManager.GetString("EUROPE_BELARUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosnia and Herzegovina.
        /// </summary>
        public static string EUROPE_BOSNIA {
            get {
                return ResourceManager.GetString("EUROPE_BOSNIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brussels.
        /// </summary>
        public static string EUROPE_BRUSSELS {
            get {
                return ResourceManager.GetString("EUROPE_BRUSSELS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulgaria.
        /// </summary>
        public static string EUROPE_BULGARIA {
            get {
                return ResourceManager.GetString("EUROPE_BULGARIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatia.
        /// </summary>
        public static string EUROPE_CROATIA {
            get {
                return ResourceManager.GetString("EUROPE_CROATIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyprus.
        /// </summary>
        public static string EUROPE_CYPRUS {
            get {
                return ResourceManager.GetString("EUROPE_CYPRUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czech Republic.
        /// </summary>
        public static string EUROPE_CZECH {
            get {
                return ResourceManager.GetString("EUROPE_CZECH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denmark.
        /// </summary>
        public static string EUROPE_DENMARK {
            get {
                return ResourceManager.GetString("EUROPE_DENMARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estonia.
        /// </summary>
        public static string EUROPE_ESTONIA {
            get {
                return ResourceManager.GetString("EUROPE_ESTONIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finland.
        /// </summary>
        public static string EUROPE_FINLAND {
            get {
                return ResourceManager.GetString("EUROPE_FINLAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to France.
        /// </summary>
        public static string EUROPE_FRANCE {
            get {
                return ResourceManager.GetString("EUROPE_FRANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Germany.
        /// </summary>
        public static string EUROPE_GERMANY {
            get {
                return ResourceManager.GetString("EUROPE_GERMANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greece.
        /// </summary>
        public static string EUROPE_GREECE {
            get {
                return ResourceManager.GetString("EUROPE_GREECE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holland.
        /// </summary>
        public static string EUROPE_HOLLAND {
            get {
                return ResourceManager.GetString("EUROPE_HOLLAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hungary.
        /// </summary>
        public static string EUROPE_HUNGARY {
            get {
                return ResourceManager.GetString("EUROPE_HUNGARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ireland.
        /// </summary>
        public static string EUROPE_IRELAND {
            get {
                return ResourceManager.GetString("EUROPE_IRELAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italy.
        /// </summary>
        public static string EUROPE_ITALY {
            get {
                return ResourceManager.GetString("EUROPE_ITALY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latvia.
        /// </summary>
        public static string EUROPE_LATVIA {
            get {
                return ResourceManager.GetString("EUROPE_LATVIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liechtenstein.
        /// </summary>
        public static string EUROPE_LIECHTENSTEIN {
            get {
                return ResourceManager.GetString("EUROPE_LIECHTENSTEIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lithuania.
        /// </summary>
        public static string EUROPE_LITHUANIA {
            get {
                return ResourceManager.GetString("EUROPE_LITHUANIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luxembourg.
        /// </summary>
        public static string EUROPE_LUXEMBOURG {
            get {
                return ResourceManager.GetString("EUROPE_LUXEMBOURG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macedonia.
        /// </summary>
        public static string EUROPE_MACEDONIA {
            get {
                return ResourceManager.GetString("EUROPE_MACEDONIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malta.
        /// </summary>
        public static string EUROPE_MALTA {
            get {
                return ResourceManager.GetString("EUROPE_MALTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOLDOVA.
        /// </summary>
        public static string EUROPE_MOLDOVA {
            get {
                return ResourceManager.GetString("EUROPE_MOLDOVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monaco.
        /// </summary>
        public static string EUROPE_MONACO {
            get {
                return ResourceManager.GetString("EUROPE_MONACO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montenegro.
        /// </summary>
        public static string EUROPE_MONTENEGRO {
            get {
                return ResourceManager.GetString("EUROPE_MONTENEGRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norway.
        /// </summary>
        public static string EUROPE_NORWAY {
            get {
                return ResourceManager.GetString("EUROPE_NORWAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poland.
        /// </summary>
        public static string EUROPE_POLAND {
            get {
                return ResourceManager.GetString("EUROPE_POLAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portugal.
        /// </summary>
        public static string EUROPE_PORTUGAL {
            get {
                return ResourceManager.GetString("EUROPE_PORTUGAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romania.
        /// </summary>
        public static string EUROPE_ROMANIA {
            get {
                return ResourceManager.GetString("EUROPE_ROMANIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russia.
        /// </summary>
        public static string EUROPE_RUSSIA {
            get {
                return ResourceManager.GetString("EUROPE_RUSSIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to San Marino.
        /// </summary>
        public static string EUROPE_SAN_MARINO {
            get {
                return ResourceManager.GetString("EUROPE_SAN_MARINO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serbia.
        /// </summary>
        public static string EUROPE_SERBIA {
            get {
                return ResourceManager.GetString("EUROPE_SERBIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovakia.
        /// </summary>
        public static string EUROPE_SLOVAKIA {
            get {
                return ResourceManager.GetString("EUROPE_SLOVAKIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovenia.
        /// </summary>
        public static string EUROPE_SLOVENIA {
            get {
                return ResourceManager.GetString("EUROPE_SLOVENIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spain.
        /// </summary>
        public static string EUROPE_SPAIN {
            get {
                return ResourceManager.GetString("EUROPE_SPAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweden.
        /// </summary>
        public static string EUROPE_SWEDEN {
            get {
                return ResourceManager.GetString("EUROPE_SWEDEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switzerland.
        /// </summary>
        public static string EUROPE_SWITZERLAND {
            get {
                return ResourceManager.GetString("EUROPE_SWITZERLAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkey.
        /// </summary>
        public static string EUROPE_TURKEY {
            get {
                return ResourceManager.GetString("EUROPE_TURKEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United Kingdom.
        /// </summary>
        public static string EUROPE_UK {
            get {
                return ResourceManager.GetString("EUROPE_UK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukraine.
        /// </summary>
        public static string EUROPE_UKRAIN {
            get {
                return ResourceManager.GetString("EUROPE_UKRAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vatican City.
        /// </summary>
        public static string EUROPE_VATICAN {
            get {
                return ResourceManager.GetString("EUROPE_VATICAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budapest.
        /// </summary>
        public static string HUNGARY_BUDAPEST {
            get {
                return ResourceManager.GetString("HUNGARY_BUDAPEST", resourceCulture);
            }
        }
    }
}
